Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0ea0f26a6d50850c5
    DependsOn: MyDB

  MyDB:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: '5'
      DBInstanceClass: db.t2.micro
      Engine: MYSQL
      EngineVersion: "8.0.28"
      MasterUsername: Admin
      MasterUserPassword: password
    DeletionPolicy: Delete