# @format
Mappings:
  RegionMap:
    eu-west-1:
      "32": "ami-0ea0f26a6d50850c5"
      "64": "ami-062cd09187a31b743"
    eu-central-1:
      "32": "ami-05ff5eaef6149df49"
      "64": "ami-0d9de36666c01a9ca"

Parameters:
  SecurityGroupDescription:
    Description: Security Group Description
    Type: String

Resources:
  #EC2
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: eu-west-1a
      InstanceType: t2.micro
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", 32]
      SecurityGroups:
        - !Ref SSHSecurityGroup
        - !Ref ServerSecurityGroup

  # an elastic IP for our instance
  #  MyEIP:
  #    Type: AWS::EC2::EIP
  #    Properties:
  #      InstanceId: !Ref MyInstance

  # our EC2 Security group
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22

  # our second EC2 Security group
  ServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Ref SecurityGroupDescription
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
        - CidrIp: 0.0.0.0/0
          FromPort: 80
          IpProtocol: tcp
          ToPort: 80
